server:
  port: 80
---
spring:
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://localhost:8080/
          predicates:
            - Path=/api/**
        - id: web
          uri: http://localhost:9090/
          predicates:
            - Path=/web/**
          filters:
            - StripPrefix=1

